u1 = User.create :first_name => 'Freddie', :last_name => 'Butcher', :email => 'freddiebutcher@gmail.com', :isadmin => 'true', :password => 'chicken'
u2 = User.create :first_name => 'Ratsamee', :last_name => 'Kajornchaiyakul', :email => 'meekaj@gmail.com', :isadmin => 'false', :password => 'chicken'
u3 = User.create :first_name => 'Harrison', :last_name => 'Malouf', :email => 'harrisonmalouf@gmail.com', :isadmin => 'false', :password => 'chicken'
u4 = User.create :first_name => 'Sienna', :last_name => 'Miller', :email => 'siennamiller@gmail.com', :isadmin => 'false', :password => 'chicken'
u5 = User.create :first_name => 'Bradley', :last_name => 'Pittance', :email => 'bradpitt@gmail.com', :isadmin => 'false', :password => 'chicken'
